---
# tasks file for apache
  - name: install apache
    yum:
      name: httpd
      state: latest
  - name: Start & enable apache
    service:
      name: httpd
      state: started
      enabled: yes
  - name: copy static index.html to apache directory 
    template:
      src: index.html.j2
      dest: /var/www/html/index.html
      mode: 0644
  - name: Start & enable apache
    service:
      name: httpd
      state: restarted

