---
- name: configure repos
  hosts: all
  gather_facts: false
  become: true
  tasks:
  roles:
    - app-repo

- name: deploy haproxy
  hosts: frontends
  gather_facts: false
  become: true
  tasks:
  roles:
    - haproxy

- name: deploy app-tier & apache
  hosts: apps
  gather_facts: false
  become: true
  tasks:
  roles:
    - app-tier
    - apache 

- name: deploy postgres 
  hosts: appdbs
  gather_facts: false
  become: true
  tasks:
  roles:
    - postgres



